## Import the numpy package under the name np

In [1]:
import numpy as np

## Print the numpy version and the configuration

In [2]:
print(np.__version__)

1.9.3


## Create a null vector of size 10

In [4]:
Z = np.zeros((3,3))
print(Z)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


## Create a vector with values ranging from 10 to 49 

In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Reverse a vector (first element becomes last)

In [7]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## Find indices of non-zero elements from [1,2,0,0,4,0] 

In [130]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


## Create a 3x3 identity matrix 

In [131]:
Z = np.eye(3)
print(Z)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Create a 3x3x3 array with random values

In [132]:
Z = np.random.random((3,3,3))
print(Z)

[[[ 0.12505215  0.54966634  0.23834015]
  [ 0.3917796   0.27394895  0.88417423]
  [ 0.74949434  0.07568665  0.26245262]]

 [[ 0.16308828  0.36385225  0.5028986 ]
  [ 0.44287233  0.0671464   0.23769351]
  [ 0.78110436  0.05306855  0.45204465]]

 [[ 0.92706123  0.75180019  0.57556319]
  [ 0.52943173  0.05633231  0.01991459]
  [ 0.82962773  0.24395021  0.78288922]]]


## Create a 10x10 array with random values and find the minimum and maximum values

In [133]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00648402429948 0.997385399456


## Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [134]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Create a 8x8 matrix and fill it with a checkerboard pattern 

In [135]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Create a checkerboard 8x8 matrix using the tile function

In [22]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Normalize a 5x5 random matrix 

In [24]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.03562917  0.00485119  0.61760072  0.02889611  0.        ]
 [ 0.2101583   0.71628241  0.33110041  0.53238597  0.67820013]
 [ 0.24986278  0.60703533  0.46993269  0.14863664  0.94221083]
 [ 0.87096978  0.48069485  0.31863881  0.33168358  1.        ]
 [ 0.99277304  0.40817982  0.78382338  0.85077955  0.85144464]]


## Create a 5x5 matrix with row values ranging from 0 to 4 

In [26]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [28]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


## Create a random vector of size 10 and sort it 

In [30]:
Z = np.random.random(10)
Z.sort()
print(Z)

[ 0.10276366  0.20191567  0.22568041  0.32489088  0.3285051   0.33352224
  0.39807171  0.76821316  0.81474889  0.85945833]


## Consider two random array A anb B, check if they are equal 

In [32]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


## Make an array immutable (read-only)

In [34]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

## Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [37]:
Z = np.random.random((3,3))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 0.80550945  0.66025397  0.50540393]
[ 0.72562489  0.37537555  0.2332886 ]


## Create random vector of size 10 and replace the maximum value by 0

In [39]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[ 0.52228505  0.6806661   0.55631029  0.83490012  0.37489962  0.70159677
  0.          0.34099381  0.49790122  0.61126664]


## Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [43]:
Z = np.zeros((3,3), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
print(Z)

[[(0.0, 0.0) (0.5, 0.0) (1.0, 0.0)]
 [(0.0, 0.5) (0.5, 0.5) (1.0, 0.5)]
 [(0.0, 1.0) (0.5, 1.0) (1.0, 1.0)]]


## Create a structured array representing a position (x,y) and a color (r,g,b) 

In [46]:
 Z = np.zeros(3, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0))]


## Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [49]:
Z = np.random.random((3,3))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((3,3))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          0.4920944   0.55956555]
 [ 0.4920944   0.          0.07017518]
 [ 0.55956555  0.07017518  0.        ]]
[[ 0.          0.70058124  0.86626901]
 [ 0.70058124  0.          1.21179983]
 [ 0.86626901  1.21179983  0.        ]]


## Generate a generic 2D Gaussian-like array

In [51]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

## How to randomly place p elements in a 2D array ?

In [54]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)

print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


## Subtract the mean of each row of a matrix 

In [58]:

X = np.random.rand(3, 3)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

[[ 0.22583532 -0.13036163 -0.09547369]
 [ 0.22878281 -0.28065019  0.05186739]
 [-0.32953026  0.2645446   0.06498566]]


## How to I sort an array by the nth column ? 

In [60]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 1 8]
 [1 2 8]
 [3 5 3]]
[[3 1 8]
 [1 2 8]
 [3 5 3]]


## How to tell if a given 2D array has null columns ?

In [63]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


## Find the nearest value from a given value in an array

In [65]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.46958006569


## Consider a generator function that generates 10 integers and use it to build an array 

In [68]:
def generate():
    for x in range(0,10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


## Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices) ? 

In [70]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[ 2.  2.  3.  3.  1.  4.  3.  3.  7.  2.]


## How to accumulate elements of a vector (X) to an array (F) based on an index list (I) ? 

In [72]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


## Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

In [74]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


## Considering a four dimensions array, how to get sum over the last two axis at once ?

In [76]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 52 55 55]
 [60 55 19 59]
 [59 48 52 49]]


## Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices ?

In [81]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[ 0.39675704  0.57471862  0.47193121  0.54390243  0.49348064  0.64146048
  0.40499173  0.50708171  0.5901638   0.55288165]


## How to get the diagonal of a dot product ? 

In [143]:
A = np.random.randint(0, 10,(2,2))
B = np.random.randint(0,10, (2,2))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)


array([14,  7])

## Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value ? 

In [85]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


## Consider an array of dimension (5,5,3), how to mulitply it by an array 
## with dimensions (5,5) ? 

In [136]:
A = np.ones((2,2,3))
B = 2*np.ones((2,2))
print(A * B[:,:,None])

[[[ 2.  2.  2.]
  [ 2.  2.  2.]]

 [[ 2.  2.  2.]
  [ 2.  2.  2.]]]


## How to swap two rows of an array ?

In [89]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Consider a set of 10 triplets describing 10 triangles (with shared vertices), 
## find the set of unique line segments composing all the triangles 

In [91]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(11, 37) (11, 61) (15, 78) (15, 91) (17, 22) (17, 45) (22, 45) (23, 77)
 (23, 81) (30, 54) (30, 62) (30, 77) (30, 82) (37, 61) (39, 54) (39, 62)
 (54, 62) (54, 82) (57, 60) (57, 69) (60, 69) (62, 77) (67, 79) (67, 94)
 (75, 82) (75, 94) (77, 81) (78, 91) (79, 94) (82, 94)]


## Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C ? 

In [93]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


## How to compute averages using a sliding window over an array ? 

In [95]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.
  16.  17.  18.]


## Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) 

In [97]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


## How to negate a boolean, or to change the sign of a float inplace ? 

In [99]:
Z = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

NameError: name 'arr' is not defined

## Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) 

In [101]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 3 3 7 3 9 2 3 4 9]
 [6 1 3 9 7 3 0 7 9 1]
 [0 8 5 0 3 9 0 6 9 9]
 [6 4 2 8 2 4 0 7 0 3]
 [6 2 0 6 4 6 1 3 6 5]
 [0 9 3 8 6 8 6 1 8 3]
 [5 3 5 9 2 2 5 3 7 9]
 [4 7 2 6 9 3 0 2 5 5]
 [2 7 9 7 8 3 9 6 6 3]
 [3 5 2 6 4 9 2 1 5 5]]
[[0 0 0 0 0]
 [0 4 3 3 7]
 [0 6 1 3 9]
 [0 0 8 5 0]
 [0 6 4 2 8]]


## Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]] ?

In [104]:
Z = np.arange(1,15)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[          1  8589934592           2 12884901888]
 [ 8589934592           2 12884901888           3]
 [          2 12884901888           3 17179869184]
 [12884901888           3 17179869184           4]
 [          3 17179869184           4 21474836480]
 [17179869184           4 21474836480           5]
 [          4 21474836480           5 25769803776]
 [21474836480           5 25769803776           6]
 [          5 25769803776           6 30064771072]
 [25769803776           6 30064771072           7]
 [          6 30064771072           7 34359738368]]


## Compute a matrix rank 

In [107]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


## Extract all the contiguous 3x3 blocks from a random 10x10 matrix 

In [110]:
Z = np.random.randint(0,2,(2,2))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[]


## Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [112]:
class Symetric(np.ndarray):
    def __setitem__(self, (i,j), value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

SyntaxError: invalid syntax (<ipython-input-112-7ff28b431b82>, line 2)

## Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once ? (result has shape (n,1)) 

In [115]:
# Author: Stefan van der Walt

p, n = 2, 2
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[ 4.]
 [ 4.]]


## Consider a 16x16 array, how to get the block-sum (block size is 4x4) ? 

In [138]:
# Author: Robert Kern

Z = np.ones(16,16)
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)

TypeError: data type not understood

## Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 

In [119]:

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


## Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B ? 

In [121]:

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 2 3 7]


## Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) 

In [123]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[2 4 0]
 [2 3 3]
 [0 1 3]
 [0 0 1]
 [1 2 4]
 [1 0 0]
 [2 0 1]
 [3 2 1]
 [4 4 3]
 [4 2 3]]
[[2 4 0]
 [2 3 3]
 [0 1 3]
 [0 0 1]
 [1 2 4]
 [1 0 0]
 [2 0 1]
 [3 2 1]
 [4 4 3]
 [4 2 3]]


## Convert a vector of ints into a matrix binary representation

In [125]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


## Given a two dimensional array, how to extract unique rows ?

In [127]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]
